// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktvnuwqqsfnaaxmyeeob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0dm51d3Fxc2ZuYWF4bXllZW9iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNTU0MTIsImV4cCI6MjA3NDYzMTQxMn0.kv6KybOuMKsDwu-KnNiDXcs_SgjqHbt-SIickMAdY7Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});